### ISSUE TITLE
Unrecognized architecture:aarch64

### ISSUE THREAD

**Issue by advancedwebdeveloper** [apache/openwhisk-cli#504]
Hi.

Unsure why - but I can't compile your project on an Aarch64 server.

> $ ./gradlew
> Downloading https://services.gradle.org/distributions/gradle-6.8.3-all.zip
> ..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%
> 
> Welcome to Gradle 6.8.3!
> 
> Here are the highlights of this release:
>  - Faster Kotlin DSL script compilation
>  - Vendor selection for Java toolchains
>  - Convenient execution of tasks in composite builds
>  - Consistent dependency resolution
> 
> For more details see https://docs.gradle.org/6.8.3/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/oceanfish81/openwhisk-cli/build.gradle' line: 29
> 
> * What went wrong:
> An exception occurred applying plugin request [id: 'com.github.blindpirate.gogradle', version: '0.10']
> > Failed to apply plugin 'com.github.blindpirate.gogradle'.
>    > Could not create task ':goBuild'.
>       > Could not create task of type 'GoBuild'.
>          > Unrecognized architecture:aarch64
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Here are some insights on my environment:

> $ mvn --version && gradle --version && java -version && javac -version && uname -a
> Apache Maven 3.6.3
> Maven home: /usr/share/maven
> Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-arm64
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "5.4.0-40-generic", arch: "aarch64", family: "unix"
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/java/groovy-all.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 
> ------------------------------------------------------------
> Gradle 4.4.1
> ------------------------------------------------------------
> 
> Build time:   2012-12-21 00:00:00 UTC
> Revision:     none
> 
> Groovy:       2.4.17
> Ant:          Apache Ant(TM) version 1.10.7 compiled on October 24 2019
> JVM:          14.0.2 (Private Build 14.0.2+12-Ubuntu-120.04)
> OS:           Linux 5.4.0-40-generic aarch64
> 
> openjdk version "14.0.2" 2020-07-14
> OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
> OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
> javac 14.0.2
> Linux ord4-c2-large-arm-01 5.4.0-40-generic #44-Ubuntu SMP Mon Jun 22 23:59:48 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
> 

Hope this helps.

P.S. Server was provided via https://www.worksonarm.com/ - CC @vielmetti

**Comment by vielmetti** [comment]
Support for arm64 in `gogradle` was merged in in https://github.com/gogradle/gogradle/pull/271 so I think it's likely that if `gogradle` was brought forward to a current version that builds would work.

The relevant code is at 

https://github.com/apache/openwhisk-cli/blob/92c251f5d3a873029ccd8d815409582301d1103d/build.gradle#L28-L31

**Comment by advancedwebdeveloper** [comment]
@vielmetti , thanks for the tip.

Now I got another issue:

> > Configure project :
> Found go 1.16.2 in /usr/local/go/bin/go, use it.
> 
> > Task :tests:createKeystore FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/oceanfish81/openwhisk-cli/tests/build.gradle' line: 63
> 
> * What went wrong:
> Execution failed for task ':tests:createKeystore'.
> > java.io.FileNotFoundException: /home/oceanfish81/openwhisk-cli/openwhisk/whisk.properties (No such file or directory)
> 
> * Try:
> Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tests:createKeystore'.
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
>         at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:184)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
>         at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
>         at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /home/oceanfish81/openwhisk-cli/openwhisk/whisk.properties (No such file or directory)
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
>         at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:525)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
>         at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:479)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:462)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$400(ExecuteActionsTaskExecuter.java:105)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:273)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:251)
>         at org.gradle.internal.execution.steps.ExecuteStep.lambda$executeOperation$1(ExecuteStep.java:66)
>         at org.gradle.internal.execution.steps.ExecuteStep.executeOperation(ExecuteStep.java:66)
>         at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:34)
>         at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
>         at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:44)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
>         at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:34)
>         at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:72)
>         at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:42)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:53)
>         at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:39)
>         at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:44)
>         at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:77)
>         at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:58)
>         at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:54)
>         at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:32)
>         at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:57)
>         at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:38)
>         at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:63)
>         at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:30)
>         at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:176)
>         at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:76)
>         at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
>         at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:43)
>         at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:32)
>         at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:39)
>         at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:25)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:102)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:95)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
>         at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:83)
>         at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
>         at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:96)
>         at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:52)
>         at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:83)
>         at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:54)
>         at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
>         at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:88)
>         at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:88)
>         at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
>         at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
>         at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:46)
>         at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:34)
>         at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:43)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$3.withWorkspace(ExecuteActionsTaskExecuter.java:286)
>         at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:43)
>         at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:33)
>         at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:40)
>         at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:30)
>         at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:54)
>         at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:40)
>         at org.gradle.internal.execution.impl.DefaultExecutionEngine.rebuild(DefaultExecutionEngine.java:46)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$0(ExecuteActionsTaskExecuter.java:182)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:182)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
>         at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
>         at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
>         at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
>         at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
> Caused by: java.io.FileNotFoundException: /home/oceanfish81/openwhisk-cli/openwhisk/whisk.properties (No such file or directory)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at build_eon1mvrgbq24nqo0n7o6cpg06$_run_closure7$_closure11.doCall(/home/oceanfish81/openwhisk-cli/tests/build.gradle:63)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at org.gradle.api.internal.AbstractTask$ClosureTaskAction.doExecute(AbstractTask.java:681)
>         at org.gradle.api.internal.AbstractTask$ClosureTaskAction.lambda$execute$0(AbstractTask.java:668)
>         at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication.reapply(DefaultUserCodeApplicationContext.java:86)
>         at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:668)
>         at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:643)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)

**Comment by advancedwebdeveloper** [comment]
I had to correct some additional stuff:

> $./gradlew goBuild --info

> Initialized native services in: /home/oceanfish81/.gradle/native
> The client will now receive all logging from the daemon (pid: 25850). The daemon log file: /home/oceanfish81/.gradle/daemon/6.8.3/daemon-25850.out.log
> Starting 15th build in daemon [uptime: 35 mins 56.485 secs, performance: 100%, non-heap usage: 34% of 256 MiB]
> Using 32 worker leases.
> Watching the file system is disabled
> Starting Build
> Settings evaluated using settings file '/home/oceanfish81/openwhisk-cli/settings.gradle'.
> Projects loaded. Root project using build file '/home/oceanfish81/openwhisk-cli/build.gradle'.
> Included projects: [root project 'openwhisk-cli', project ':tests']
> 
> > Configure project :
> Evaluating root project 'openwhisk-cli' using build file '/home/oceanfish81/openwhisk-cli/build.gradle'.
> Found go 1.16.2 in /usr/local/go/bin/go, use it.
> Ignore packages globally: appengine,a,gen,shared,common,thrifttest,appengine_internal,thrift,tutorial
> 
> > Configure project :tests
> Evaluating project ':tests' using build file '/home/oceanfish81/openwhisk-cli/tests/build.gradle'.
> All projects evaluated.
> Selected primary task 'goBuild' from project :
> Tasks to be executed: [task ':getGoBinData', task ':goI18n', task ':goPrepare', task ':resolveBuildDependencies', task ':installDependencies', task ':buildDarwinAmd64', task ':buildLinux386', task ':buildLinuxAmd64', task ':buildLinuxArm', task ':buildLinuxArm64', task ':buildLinuxPpc64le', task ':buildLinuxS390x', task ':buildWindows386', task ':buildWindowsAmd64', task ':goBuild']
> Tasks that were excluded: []
> :getGoBinData (Thread[Execution worker for ':',5,main]) started.
> 
> > Task :getGoBinData
> Caching disabled for task ':getGoBinData' because:
>   Build cache is disabled
> Task ':getGoBinData' is not up-to-date because:
>   Task has not declared any outputs despite executing actions.
> Starting process 'command 'go''. Working directory: /home/oceanfish81/openwhisk-cli Command: go get -u github.com/jteeuwen/go-bindata/...
> Successfully started process 'command 'go''
> [go, get, -u, github.com/jteeuwen/go-bindata/...]
> :getGoBinData (Thread[Execution worker for ':',5,main]) completed. Took 0.654 secs.
> :goI18n (Thread[Execution worker for ':',5,main]) started.
> 
> > Task :goI18n FAILED
> Caching disabled for task ':goI18n' because:
>   Build cache is disabled
> Task ':goI18n' is not up-to-date because:
>   Task has not declared any outputs despite executing actions.
> Starting process 'command 'go-bindata''. Working directory: /home/oceanfish81/openwhisk-cli Command: go-bindata -pkg wski18n -o wski18n/i18n_resources.go wski18n/resources
> :goI18n (Thread[Execution worker for ':',5,main]) completed. Took 0.014 secs.

Hence that I didn't get any error, when trying to execute

> $ go-bindata -pkg wski18n -o wski18n/i18n_resources.go wski18n/resources
